#ifndef _INFO_ERROR_H
#define _INFO_ERROR_H

enum class INFO
{
    SUCCESS,
    UNINITIALIZED_OBJECT,
    NULL_POINTER,
    INVALID_VALUE,
    INVALID_INDEX,
    DOMAIN_MISMATCH,
    DIMENSION_MISMATCH,
    OUTPUT_NOT_EMPTY,
    NO_VALUE,
    OUT_OF_MEMORY,
    INSUFFICIENT_SPACE,
    INVALID_OBJECT,
    INDEX_OUT_OF_BOUNDS,
    PANIC,
    NOT_ALLOWED,
    NOT_IMPLEMENTED,
    UNKNOWN_SORT_POLICY,
    BLK_DIM_NOTSET
};

enum class IO_INFO
{
    SUCCESS,
    FILE_ERROR,
    COMPLEX_NOT_SUPPORTED,
    DENSE_NOT_SUPPORTED,
    NOT_A_MATRIX,
    HERMITIAN_NOT_SUPPORTED,
    UNKNOWN_FORMAT,
    UNKNOWN_FIELD_TYPE,
    UNKNOWN_SYMMETRY,
    MEM_ERROR,
    DENSE_SYMMETRY_NOT_SUPPORTED,
    DENSE_PATTERN_NOT_SUPPORTED   
};

#endif